title: Praful Thapa
email: prafulthapa97@gmail.com
description: Project Manager | Blog | Portfolio
author: Praful Thapa
baseurl: ""
url: "https://prafulthapa.com" # the base hostname & protocol for your site

# Social Profiles
twitter_username: Praful611793
github_username: prass07
facebook_username: praful.thapa.2025
instagram_username: prafulthapa97
linkedin_username: praful-thapa

# Add your google-analytics ID here to activate google analytics
google_analytics: G-Q3RZ2MBSM4 # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
